# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.1.1

before_script:
- php composer.phar update


# Set any variables we need
variables:

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:
  script: